print ("###########################")
print ("#                         #")
print ("#  Valencia Angelin Nata  #")
print ("#      2210817220030      #")
print ("#                         #")
print ("###########################")